# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_source_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=512)),
                ('author', models.CharField(max_length=255)),
                ('summary', models.TextField(default='')),
                ('sent', models.BooleanField(default=False)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='source',
            name='contents',
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletters.Source'),
        ),
    ]
