# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_auto_20170730_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='entry',
            name='url',
            field=models.URLField(max_length=2083),
        ),
    ]
